# Generated by Django 3.1.3 on 2020-12-09 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_string', models.BooleanField(default=False)),
                ('puzzle_string', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81)),
                ('try_solve', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('too_few_clues', models.BooleanField(default=False)),
                ('no_solution', models.BooleanField(default=False)),
                ('multiple_solution', models.BooleanField(default=False)),
                ('multi_fill_1', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81)),
                ('multi_fill_2', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81)),
                ('puzzle_solution', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81)),
                ('error_description', models.CharField(default='', max_length=100)),
                ('difficulty', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BoxValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_value', models.CharField(blank=True, help_text='Enter only values between 1 and 9 or leave blank', max_length=1, null=True, validators=[django.core.validators.RegexValidator('[1-9]', 'Only numbers from 1 to 9 allowed')])),
                ('box_index', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solver.parent')),
            ],
        ),
    ]
