# Generated by Django 3.1.3 on 2020-12-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='error_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
