# Generated by Django 3.1.3 on 2020-12-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_auto_20201209_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='solve_attempt',
            field=models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81),
        ),
    ]
