# Generated by Django 3.1.3 on 2020-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_parent_solve_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
